[package]
name = "circuit"
version = "0.1.0"
edition = "2024"
default-run = "circuit"

[dependencies]
eframe = "0.31.1"
egui_extras = "0.31.1"
env_logger = "0.11.8"
glam = "0.30.3"
serde_json = "1.0.140"

[[bin]]
name = "circuit"
path = "src/main.rs"

[[bin]]
name = "sim"
path = "src/sim.rs"
